# Generated by Django 4.0.4 on 2022-10-17 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=40)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures')),
            ],
        ),
    ]
