# Generated by Django 4.0.4 on 2022-10-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_posts_image_alter_posts_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='body',
            new_name='cuerpo',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='posts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
